// Веб-версия спец иализаций - используем только emoji иконки
// SVG компоненты не импортируются для упрощения

export interface SpecializationOption {
  id: string;
  name: string;
  icon: string; // emoji иконка (fallback)
  iconPath?: string; // путь к SVG иконке (приоритет)
  parentIds?: string[]; // ID родительских категорий (если это подкатегория)
  isParent?: boolean; // Является ли это родительской категорией
}

export const PARENT_CATEGORIES: SpecializationOption[] = [
  {
    id: 'repair_construction',
    name: 'Ремонт и строительство',
    icon: '🏗️',
    iconPath: '/icons/specializations/construction.svg',
    isParent: true,
  },
  {
    id: 'auto_business',
    name: 'Автомобильный бизнес',
    icon: '🚗',
    iconPath: '/icons/specializations/mini-car.svg',
    isParent: true,
  },
  {
    id: 'administrative_staff',
    name: 'Административный персонал',
    icon: '📋',
    iconPath: '/icons/specializations/administrative-assistant.svg',
    isParent: true,
  },
  {
    id: 'security',
    name: 'Безопасность',
    icon: '🛡️',
    iconPath: '/icons/specializations/shield.svg',
    isParent: true,
  },
  {
    id: 'senior_management',
    name: 'Высший и средний менеджмент',
    icon: '👔',
    iconPath: '/icons/specializations/ceo.svg',
    isParent: true,
  },
  {
    id: 'raw_materials_extraction',
    name: 'Добыча сырья',
    icon: '⛏️',
    iconPath: '/icons/specializations/drilling-process.svg',
    isParent: true,
  },
  {
    id: 'household_service_staff',
    name: 'Домашний, обслуживающий персонал',
    icon: '🏠',
    iconPath: '/icons/specializations/waitress.svg',
    isParent: true,
  },
  {
    id: 'procurement',
    name: 'Закупки',
    icon: '📦',
    iconPath: '/icons/specializations/grocery.svg',
    isParent: true,
  },
  {
    id: 'information_technology',
    name: 'Информационные технологии',
    icon: '💻',
    iconPath: '/icons/specializations/web-developer.svg',
    isParent: true,
  },
  {
    id: 'arts_entertainment_media',
    name: 'Искусство, развлечения, массмедиа',
    icon: '🎭',
    iconPath: '/icons/specializations/painting.svg',
    isParent: true,
  },
  {
    id: 'marketing_advertising_pr',
    name: 'Маркетинг, реклама, PR',
    icon: '📢',
    iconPath: '/icons/specializations/marketing.svg',
    isParent: true,
  },
  {
    id: 'medicine_pharma',
    name: 'Медицина, фармацевтика',
    icon: '⚕️',
    iconPath: '/icons/specializations/medicine.svg',
    isParent: true,
  },
  {
    id: 'science_education',
    name: 'Наука, образование',
    icon: '📚',
    iconPath: '/icons/specializations/science-book.svg',
    isParent: true,
  },
  {
    id: 'sales_customer_service',
    name: 'Продажи, обслуживание клиентов',
    icon: '💼',
    iconPath: '/icons/specializations/sales-pipeline.svg',
    isParent: true,
  },
  {
    id: 'production_service',
    name: 'Производство, сервисное обслуживание',
    icon: '⚙️',
    iconPath: '/icons/specializations/service-tools.svg',
    isParent: true,
  },
  {
    id: 'working_personnel',
    name: 'Рабочий персонал',
    icon: '🔧',
    iconPath: '/icons/specializations/delivery-man.svg',
    isParent: true,
  },
  {
    id: 'retail',
    name: 'Розничная торговля',
    icon: '🛍️',
    iconPath: '/icons/specializations/shopping-bag.svg',
    isParent: true,
  },
  {
    id: 'agriculture',
    name: 'Сельское хозяйство',
    icon: '🌾',
    iconPath: '/icons/specializations/growing-seed.svg',
    isParent: true,
  },
  {
    id: 'sports_fitness_beauty',
    name: 'Спортивные клубы, фитнес, салоны красоты',
    icon: '💪',
    iconPath: '/icons/specializations/weightlifting.svg',
    isParent: true,
  },
  {
    id: 'strategy_investment_consulting',
    name: 'Стратегия, инвестиции, консалтинг',
    icon: '📈',
    iconPath: '/icons/specializations/consulting.svg',
    isParent: true,
  },
  {
    id: 'insurance',
    name: 'Страхование',
    icon: '🛡️',
    iconPath: '/icons/specializations/insurance.svg',
    isParent: true,
  },
  {
    id: 'transport_logistics',
    name: 'Транспорт, логистика, перевозки',
    icon: '🚚',
    iconPath: '/icons/specializations/delivery-truck.svg',
    isParent: true,
  },
  {
    id: 'tourism_hotels_restaurants',
    name: 'Туризм, гостиницы, рестораны',
    icon: '🏨',
    iconPath: '/icons/specializations/hotel-rating-building-stars.svg',
    isParent: true,
  },
  {
    id: 'hr_training',
    name: 'Управление персоналом, тренинги',
    icon: '👥',
    iconPath: '/icons/specializations/hr.svg',
    isParent: true,
  },
  {
    id: 'finance_accounting',
    name: 'Финансы, бухгалтерия',
    icon: '💰',
    iconPath: '/icons/specializations/financing.svg',
    isParent: true,
  },
  {
    id: 'legal',
    name: 'Юристы',
    icon: '⚖️',
    iconPath: '/icons/specializations/justice.svg',
    isParent: true,
  },
  {
    id: 'other',
    name: 'Другое',
    icon: '📋',
    iconPath: '/icons/specializations/more.svg',
    isParent: true,
  },
];

export const SPECIALIZATIONS: SpecializationOption[] = [
{
    id: 'one_day_job',
    name: 'Работа на 1 день',
    icon: '📅',
    iconPath: '/icons/specializations/calendar-one-day.svg',
  },
{
    id: 'brigades',
    name: 'Бригады',
    icon: '👷',
    iconPath: '/icons/specializations/management.svg',
    parentIds: ['repair_construction'],
  },
  {
    id: 'plumber',
    name: 'Сантехники',
    icon: '🔧',
    iconPath: '/icons/specializations/faucet.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'electrician',
    name: 'Электрики',
    icon: '⚡',
    iconPath: '/icons/specializations/electric-power.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'painter',
    name: 'Маляр-Штукатур',
    icon: '🎨',
    iconPath: '/icons/specializations/paint-roller.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'boiler_installation',
    name: 'Установка котлов',
    icon: '🔥',
    iconPath: '/icons/specializations/gas-kotel.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'gas_electric_stoves',
    name: 'Газовые и электроплиты',
    icon: '🍳',
    iconPath: '/icons/specializations/gas-stove.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'carpenter',
    name: 'Плотники',
    icon: '🪚',
    iconPath: '/icons/specializations/saw.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'gardener',
    name: 'Садовник',
    icon: '🌱',
    iconPath: '/icons/specializations/gardening.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'air_conditioner',
    name: 'Кондиционеры',
    icon: '❄️',
    iconPath: '/icons/specializations/air-conditioner.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'washing_machine',
    name: 'Стиральные машины',
    icon: '🧺',
    iconPath: '/icons/specializations/laundry.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'turnkey_renovation',
    name: 'Ремонт под ключ',
    icon: '🏠',
    iconPath: '/icons/specializations/renovation.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'lock_repair',
    name: 'Ремонт замков',
    icon: '🔐',
    iconPath: '/icons/specializations/padlock.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'refrigerator',
    name: 'Холодильники',
    icon: '🧊',
    iconPath: '/icons/specializations/smart-refrigirator.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'doors',
    name: 'Двери',
    icon: '🚪',
    iconPath: '/icons/specializations/door.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'plastic_windows',
    name: 'Пластиковые окна',
    icon: '🪟',
    iconPath: '/icons/specializations/window.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'bricklaying',
    name: 'Кладка кирпича',
    icon: '🧱',
    iconPath: '/icons/specializations/construction.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'custom_furniture',
    name: 'Мебель на заказ',
    icon: '🪑',
    iconPath: '/icons/specializations/bed.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'welder',
    name: 'Сварщики',
    icon: '🔨',
    iconPath: '/icons/specializations/welder.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'roofer',
    name: 'Кровельщики',
    icon: '🏗️',
    iconPath: '/icons/specializations/rooftile.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'tiler',
    name: 'Плиточники',
    icon: '🟦',
    iconPath: '/icons/specializations/tile.svg',
    parentIds: ['repair_construction'],
  },
{
    id: 'car_washer',
    name: 'Автомойщик',
    icon: '🚿',
    iconPath: '/icons/specializations/worker.svg',
    parentIds: ['auto_business'],
  },
{
    id: 'auto_mechanic',
    name: 'Автослесарь, автомеханик',
    icon: '🔧',
    iconPath: '/icons/specializations/repair-3.svg',
    parentIds: ['auto_business', 'working_personnel'],
  },
{
    id: 'service_advisor',
    name: 'Мастер-приемщик',
    icon: '📋',
    iconPath: '/icons/specializations/worker-master.svg',
    parentIds: ['auto_business'],
  },
{
    id: 'sales_manager',
    name: 'Менеджер по продажам, менеджер по работе с клиентами',
    icon: '💼',
    iconPath: '/icons/specializations/fund-manager.svg',
    parentIds: ['auto_business', 'marketing_advertising_pr', 'sales_customer_service', 'sports_fitness_beauty'],
  },
{
    id: 'administrator',
    name: 'Администратор',
    icon: '👔',
    iconPath: '/icons/specializations/external-salesman.svg',
    parentIds: ['administrative_staff', 'household_service_staff', 'medicine_pharma', 'sports_fitness_beauty', 'tourism_hotels_restaurants'],
  },
  {
    id: 'records_clerk',
    name: 'Делопроизводитель, архивариус',
    icon: '📁',
    iconPath: '/icons/specializations/files.svg',
    parentIds: ['administrative_staff'],
  },
{
    id: 'courier',
    name: 'Курьер',
    icon: '📦',
    iconPath: '/icons/specializations/delivery-courier.svg',
    parentIds: ['administrative_staff', 'household_service_staff', 'transport_logistics'],
  },
{
    id: 'facility_manager',
    name: 'Менеджер/руководитель АХО',
    icon: '🏢',
    iconPath: '/icons/specializations/manager.svg',
    parentIds: ['administrative_staff', 'tourism_hotels_restaurants'],
  },
{
    id: 'data_operator',
    name: 'Оператор ПК, оператор базы данных',
    icon: '💻',
    iconPath: '/icons/specializations/customer-service.svg',
    parentIds: ['administrative_staff'],
  },
{
    id: 'office_manager',
    name: 'Офис-менеджер',
    icon: '🗂️',
    iconPath: '/icons/specializations/work.svg',
    parentIds: ['administrative_staff'],
  },
{
    id: 'translator',
    name: 'Переводчик',
    icon: '🌐',
    iconPath: '/icons/specializations/translator.svg',
    parentIds: ['administrative_staff'],
  },
{
    id: 'secretary',
    name: 'Секретарь, помощник руководителя, ассистент',
    icon: '📝',
    iconPath: '/icons/specializations/secretary.svg',
    parentIds: ['administrative_staff'],
  },
{
    id: 'security_guard',
    name: 'Охранник',
    icon: '🛡️',
    iconPath: '/icons/specializations/security-guard.svg',
    parentIds: ['security', 'household_service_staff'],
  },
{
    id: 'security_it_specialist',
    name: 'Специалист по информационной безопасности',
    icon: '🔒',
    iconPath: '/icons/specializations/personal-data.svg',
    parentIds: ['security', 'information_technology'],
  },
{
    id: 'security_service_specialist',
    name: 'Специалист службы безопасности',
    icon: '👮',
    iconPath: '/icons/specializations/police.svg',
    parentIds: ['security'],
  },
{
    id: 'ceo',
    name: 'Генеральный директор, исполнительный директор (CEO)',
    icon: '🎯',
    iconPath: '/icons/specializations/ceo.svg',
    parentIds: ['senior_management'],
  },
{
    id: 'cio',
    name: 'Директор по информационным технологиям (CIO)',
    icon: '💻',
    iconPath: '/icons/specializations/programmer.svg',
    parentIds: ['senior_management', 'information_technology'],
  },
{
    id: 'cmo',
    name: 'Директор по маркетингу и PR (CMO)',
    icon: '📢',
    iconPath: '/icons/specializations/marketing-agent.svg',
    parentIds: ['senior_management', 'marketing_advertising_pr'],
  },
{
    id: 'hrd',
    name: 'Директор по персоналу (HRD)',
    icon: '👥',
    iconPath: '/icons/specializations/career.svg',
    parentIds: ['senior_management', 'hr_training'],
  },
{
    id: 'clo',
    name: 'Директор юридического департамента (CLO)',
    icon: '⚖️',
    iconPath: '/icons/specializations/lawyer-man.svg',
    parentIds: ['senior_management', 'legal'],
  },
{
    id: 'cco',
    name: 'Коммерческий директор (CCO)',
    icon: '💰',
    iconPath: '/icons/specializations/finance.svg',
    parentIds: ['senior_management', 'sales_customer_service'],
  },
{
    id: 'production_manager',
    name: 'Начальник производства',
    icon: '🏭',
    iconPath: '/icons/specializations/production-assistant.svg',
    parentIds: ['senior_management', 'production_service'],
  },
{
    id: 'coo',
    name: 'Операционный директор (COO)',
    icon: '⚙️',
    iconPath: '/icons/specializations/management-consulting.svg',
    parentIds: ['senior_management'],
  },
{
    id: 'analytics_head',
    name: 'Руководитель отдела аналитики',
    icon: '📊',
    iconPath: '/icons/specializations/outcome.svg',
    parentIds: ['senior_management', 'information_technology'],
  },
{
    id: 'senior_logistics_head',
    name: 'Руководитель отдела логистики',
    icon: '🚚',
    iconPath: '/icons/specializations/logistics-assistant.svg',
    parentIds: ['senior_management', 'transport_logistics'],
  },
{
    id: 'marketing_head',
    name: 'Руководитель отдела маркетинга и рекламы',
    icon: '📈',
    iconPath: '/icons/specializations/sales-promoter.svg',
    parentIds: ['senior_management', 'marketing_advertising_pr'],
  },
{
    id: 'senior_hr_head',
    name: 'Руководитель отдела персонала',
    icon: '👔',
    iconPath: '/icons/specializations/job-interview.svg',
    parentIds: ['senior_management', 'hr_training'],
  },
{
    id: 'branch_manager',
    name: 'Руководитель филиала',
    icon: '🏢',
    iconPath: '/icons/specializations/enterprise.svg',
    parentIds: ['senior_management', 'sales_customer_service'],
  },
{
    id: 'cto',
    name: 'Технический директор (CTO)',
    icon: '🔧',
    iconPath: '/icons/specializations/strategic-consulting.svg',
    parentIds: ['senior_management', 'information_technology'],
  },
{
    id: 'senior_cfo',
    name: 'Финансовый директор (CFO)',
    icon: '💵',
    iconPath: '/icons/specializations/self-employed.svg',
    parentIds: ['senior_management', 'finance_accounting'],
  },
{
    id: 'geodesist',
    name: 'Геодезист',
    icon: '🗺️',
    iconPath: '/icons/specializations/surveyor.svg',
    parentIds: ['raw_materials_extraction'],
  },
{
    id: 'geologist',
    name: 'Геолог',
    icon: '🪨',
    iconPath: '/icons/specializations/geologist.svg',
    parentIds: ['raw_materials_extraction'],
  },
{
    id: 'laboratory_assistant',
    name: 'Лаборант',
    icon: '🧪',
    iconPath: '/icons/specializations/researcher.svg',
    parentIds: ['raw_materials_extraction', 'medicine_pharma', 'science_education', 'production_service'],
  },
{
    id: 'machinist',
    name: 'Машинист',
    icon: '🚜',
    iconPath: '/icons/specializations/worker-2.svg',
    parentIds: ['raw_materials_extraction', 'production_service', 'working_personnel', 'agriculture', 'transport_logistics'],
  },
{
    id: 'research_specialist',
    name: 'Научный специалист, исследователь',
    icon: '🔬',
    iconPath: '/icons/specializations/scientist.svg',
    parentIds: ['raw_materials_extraction', 'medicine_pharma', 'science_education', 'production_service'],
  },
{
    id: 'shift_supervisor',
    name: 'Начальник смены, мастер участка',
    icon: '👷',
    iconPath: '/icons/specializations/mentor.svg',
    parentIds: ['raw_materials_extraction', 'production_service'],
  },
{
    id: 'technologist',
    name: 'Технолог',
    icon: '⚗️',
    iconPath: '/icons/specializations/human-resources.svg',
    parentIds: ['raw_materials_extraction', 'production_service', 'agriculture'],
  },
{
    id: 'driver',
    name: 'Водитель',
    icon: '🚗',
    iconPath: '/icons/specializations/driver.svg',
    parentIds: ['household_service_staff', 'working_personnel', 'transport_logistics'],
  },
{
    id: 'nanny',
    name: 'Воспитатель, няня',
    icon: '👶',
    iconPath: '/icons/specializations/daycare.svg',
    parentIds: ['household_service_staff', 'science_education'],
  },
{
    id: 'janitor',
    name: 'Дворник',
    icon: '🧹',
    iconPath: '/icons/specializations/dust.svg',
    parentIds: ['household_service_staff'],
  },
{
    id: 'waiter',
    name: 'Официант, бармен, бариста',
    icon: '☕',
    iconPath: '/icons/specializations/bartender.svg',
    parentIds: ['household_service_staff', 'tourism_hotels_restaurants'],
  },
{
    id: 'cleaner',
    name: 'Уборщица, уборщик',
    icon: '🧽',
    iconPath: '/icons/specializations/cleaning-cart.svg',
    parentIds: ['household_service_staff', 'tourism_hotels_restaurants'],
  },
{
    id: 'procurement_manager',
    name: 'Менеджер по закупкам',
    icon: '🛒',
    iconPath: '/icons/specializations/shopping.svg',
    parentIds: ['procurement'],
  },
{
    id: 'tender_specialist',
    name: 'Специалист по тендерам',
    icon: '📋',
    iconPath: '/icons/specializations/task.svg',
    parentIds: ['procurement'],
  },
{
    id: 'bi_analyst',
    name: 'BI-аналитик, аналитик данных',
    icon: '📊',
    iconPath: '/icons/specializations/bar-chart.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'devops_engineer',
    name: 'DevOps-инженер',
    icon: '🔧',
    iconPath: '/icons/specializations/backend.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'it_analyst',
    name: 'Аналитик',
    icon: '📈',
    iconPath: '/icons/specializations/pie-chart.svg',
    parentIds: ['information_technology', 'marketing_advertising_pr', 'sales_customer_service', 'strategy_investment_consulting'],
  },
{
    id: 'art_director',
    name: 'Арт-директор, креативный директор',
    icon: '🎨',
    iconPath: '/icons/specializations/photo-gallery.svg',
    parentIds: ['information_technology', 'arts_entertainment_media', 'marketing_advertising_pr'],
  },
{
    id: 'business_analyst',
    name: 'Бизнес-аналитик',
    icon: '💼',
    iconPath: '/icons/specializations/document.svg',
    parentIds: ['information_technology', 'strategy_investment_consulting'],
  },
{
    id: 'game_designer',
    name: 'Гейм-дизайнер',
    icon: '🎮',
    iconPath: '/icons/specializations/videogame.svg',
    parentIds: ['information_technology', 'arts_entertainment_media'],
  },
{
    id: 'data_scientist',
    name: 'Дата-сайентист',
    icon: '🔬',
    iconPath: '/icons/specializations/virtual-lab.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'designer',
    name: 'Дизайнер, художник',
    icon: '🖌️',
    iconPath: '/icons/specializations/design.svg',
    parentIds: ['information_technology', 'arts_entertainment_media', 'marketing_advertising_pr'],
  },
{
    id: 'product_manager',
    name: 'Менеджер продукта',
    icon: '📱',
    iconPath: '/icons/specializations/assortment.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'methodologist',
    name: 'Методолог',
    icon: '📚',
    iconPath: '/icons/specializations/cheque.svg',
    parentIds: ['information_technology', 'finance_accounting'],
  },
{
    id: 'software_developer',
    name: 'Программист, разработчик',
    icon: '👨‍💻',
    iconPath: '/icons/specializations/programmer-2.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'product_analyst',
    name: 'Продуктовый аналитик',
    icon: '📊',
    iconPath: '/icons/specializations/analytics.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'dev_team_lead',
    name: 'Руководитель группы разработки',
    icon: '👥',
    iconPath: '/icons/specializations/teamwork.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'project_manager',
    name: 'Руководитель проектов',
    icon: '📋',
    iconPath: '/icons/specializations/project.svg',
    parentIds: ['information_technology', 'strategy_investment_consulting'],
  },
{
    id: 'network_engineer',
    name: 'Сетевой инженер',
    icon: '🌐',
    iconPath: '/icons/specializations/network.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'system_administrator',
    name: 'Системный администратор',
    icon: '🖥️',
    iconPath: '/icons/specializations/laptop.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'system_analyst',
    name: 'Системный аналитик',
    icon: '🔍',
    iconPath: '/icons/specializations/performance.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'system_engineer',
    name: 'Системный инженер',
    icon: '⚙️',
    iconPath: '/icons/specializations/gears.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'tech_support',
    name: 'Специалист технической поддержки',
    icon: '🛠️',
    iconPath: '/icons/specializations/customer-service-2.svg',
    parentIds: ['information_technology', 'sales_customer_service'],
  },
{
    id: 'qa_tester',
    name: 'Тестировщик',
    icon: '🧪',
    iconPath: '/icons/specializations/tester.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'technical_writer',
    name: 'Технический писатель',
    icon: '📝',
    iconPath: '/icons/specializations/content-creator.svg',
    parentIds: ['information_technology'],
  },
{
    id: 'artist_actor',
    name: 'Артист, актер, аниматор',
    icon: '🎭',
    iconPath: '/icons/specializations/actor.svg',
    parentIds: ['arts_entertainment_media'],
  },
{
    id: 'videographer',
    name: 'Видеооператор, видеомонтажер',
    icon: '🎬',
    iconPath: '/icons/specializations/cameraman.svg',
    parentIds: ['arts_entertainment_media'],
  },
{
    id: 'journalist',
    name: 'Журналист, корреспондент',
    icon: '📰',
    iconPath: '/icons/specializations/reporter.svg',
    parentIds: ['arts_entertainment_media'],
  },
{
    id: 'copywriter',
    name: 'Копирайтер, редактор, корректор',
    icon: '✍️',
    iconPath: '/icons/specializations/blog.svg',
    parentIds: ['arts_entertainment_media', 'marketing_advertising_pr'],
  },
{
    id: 'producer',
    name: 'Продюсер',
    icon: '🎥',
    iconPath: '/icons/specializations/movie.svg',
    parentIds: ['arts_entertainment_media'],
  },
{
    id: 'director',
    name: 'Режиссер, сценарист',
    icon: '🎬',
    iconPath: '/icons/specializations/director-chair.svg',
    parentIds: ['arts_entertainment_media'],
  },
{
    id: 'photographer',
    name: 'Фотограф, ретушер',
    icon: '📷',
    iconPath: '/icons/specializations/photographer.svg',
    parentIds: ['arts_entertainment_media'],
  },
{
    id: 'event_manager',
    name: 'Event-менеджер',
    icon: '🎉',
    iconPath: '/icons/specializations/event-management.svg',
    parentIds: ['marketing_advertising_pr'],
  },
{
    id: 'pr_manager',
    name: 'PR-менеджер',
    icon: '📣',
    iconPath: '/icons/specializations/advertising.svg',
    parentIds: ['marketing_advertising_pr'],
  },
{
    id: 'smm_manager',
    name: 'SMM-менеджер, контент-менеджер',
    icon: '📱',
    iconPath: '/icons/specializations/content-marketing.svg',
    parentIds: ['marketing_advertising_pr'],
  },
{
    id: 'marketing_analytics_specialist',
    name: 'Маркетолог-аналитик',
    icon: '📈',
    iconPath: '/icons/specializations/statistics.svg',
    parentIds: ['marketing_advertising_pr'],
  },
{
    id: 'marketing_manager',
    name: 'Менеджер по маркетингу, интернет-маркетолог',
    icon: '💼',
    iconPath: '/icons/specializations/phone-ad.svg',
    parentIds: ['marketing_advertising_pr'],
  },
{
    id: 'partner_manager',
    name: 'Менеджер по работе с партнерами',
    icon: '🤝',
    iconPath: '/icons/specializations/handshake.svg',
    parentIds: ['marketing_advertising_pr', 'sales_customer_service'],
  },
{
    id: 'promoter',
    name: 'Промоутер',
    icon: '📢',
    iconPath: '/icons/specializations/megaphone.svg',
    parentIds: ['marketing_advertising_pr', 'retail'],
  },
{
    id: 'medical_assistant',
    name: 'Ассистент врача',
    icon: '👨‍⚕️',
    iconPath: '/icons/specializations/file-delivery.svg',
    parentIds: ['medicine_pharma'],
  },
{
    id: 'veterinarian',
    name: 'Ветеринарный врач',
    icon: '🐾',
    iconPath: '/icons/specializations/veterinarian.svg',
    parentIds: ['medicine_pharma', 'agriculture'],
  },
{
    id: 'doctor',
    name: 'Врач',
    icon: '👨‍⚕️',
    iconPath: '/icons/specializations/doctor.svg',
    parentIds: ['medicine_pharma'],
  },
{
    id: 'chief_doctor',
    name: 'Главный врач, заведующий отделением',
    icon: '🩺',
    iconPath: '/icons/specializations/doctor-2.svg',
    parentIds: ['medicine_pharma'],
  },
{
    id: 'pharmacy_manager',
    name: 'Заведующий аптекой',
    icon: '💊',
    iconPath: '/icons/specializations/pharmacist.svg',
    parentIds: ['medicine_pharma'],
  },
{
    id: 'nurse',
    name: 'Медицинская сестра, медицинский брат',
    icon: '👩‍⚕️',
    iconPath: '/icons/specializations/nursing-technician.svg',
    parentIds: ['medicine_pharma'],
  },
{
    id: 'medical_rep',
    name: 'Медицинский представитель',
    icon: '💼',
    iconPath: '/icons/specializations/doctors-office.svg',
    parentIds: ['medicine_pharma'],
  },
{
    id: 'certification_specialist',
    name: 'Специалист по сертификации',
    icon: '📜',
    iconPath: '/icons/specializations/certificate-authority.svg',
    parentIds: ['medicine_pharma', 'sales_customer_service', 'production_service'],
  },
{
    id: 'pharmacist',
    name: 'Фармацевт-провизор',
    icon: '💊',
    iconPath: '/icons/specializations/drug-research.svg',
    parentIds: ['medicine_pharma'],
  },
{
    id: 'business_trainer',
    name: 'Бизнес-тренер',
    icon: '📊',
    iconPath: '/icons/specializations/presentation.svg',
    parentIds: ['science_education', 'hr_training'],
  },
{
    id: 'education_methodologist',
    name: 'Методист',
    icon: '📝',
    iconPath: '/icons/specializations/open-book-gear.svg',
    parentIds: ['science_education'],
  },
{
    id: 'psychologist',
    name: 'Психолог',
    icon: '🧠',
    iconPath: '/icons/specializations/observation.svg',
    parentIds: ['science_education'],
  },
{
    id: 'teacher',
    name: 'Учитель, преподаватель, педагог',
    icon: '👨‍🏫',
    iconPath: '/icons/specializations/teacher.svg',
    parentIds: ['science_education'],
  },
{
    id: 'real_estate_agent',
    name: 'Агент по недвижимости',
    icon: '🏢',
    iconPath: '/icons/specializations/estate-agent.svg',
    parentIds: ['sales_customer_service'],
  },
{
    id: 'broker',
    name: 'Брокер',
    icon: '💹',
    iconPath: '/icons/specializations/work-experience.svg',
    parentIds: ['sales_customer_service', 'finance_accounting'],
  },
{
    id: 'cashier',
    name: 'Кассир-операционист',
    icon: '💵',
    iconPath: '/icons/specializations/cashier.svg',
    parentIds: ['sales_customer_service'],
  },
{
    id: 'sales_coordinator',
    name: 'Координатор отдела продаж',
    icon: '📋',
    iconPath: '/icons/specializations/sales-pipeline-1.svg',
    parentIds: ['sales_customer_service'],
  },
{
    id: 'credit_specialist',
    name: 'Кредитный специалист',
    icon: '💳',
    iconPath: '/icons/specializations/credit-score.svg',
    parentIds: ['sales_customer_service', 'finance_accounting'],
  },
{
    id: 'call_center_operator',
    name: 'Оператор call-центра, специалист контактного центра',
    icon: '📞',
    iconPath: '/icons/specializations/support-24.svg',
    parentIds: ['sales_customer_service'],
  },
{
    id: 'sales_consultant',
    name: 'Продавец-консультант, продавец-кассир',
    icon: '🛒',
    iconPath: '/icons/specializations/financial-consultation.svg',
    parentIds: ['sales_customer_service', 'retail'],
  },
{
    id: 'customer_service_head',
    name: 'Руководитель отдела клиентского обслуживания',
    icon: '👔',
    iconPath: '/icons/specializations/info.svg',
    parentIds: ['sales_customer_service'],
  },
{
    id: 'sales_head',
    name: 'Руководитель отдела продаж',
    icon: '👔',
    iconPath: '/icons/specializations/collaborator.svg',
    parentIds: ['sales_customer_service'],
  },
{
    id: 'insurance_agent',
    name: 'Страховой агент',
    icon: '🛡️',
    iconPath: '/icons/specializations/protection.svg',
    parentIds: ['sales_customer_service', 'insurance'],
  },
{
    id: 'sales_representative',
    name: 'Торговый представитель',
    icon: '💼',
    iconPath: '/icons/specializations/shopping-2.svg',
    parentIds: ['sales_customer_service'],
  },
{
    id: 'commissioning_engineer',
    name: 'Инженер ПНР',
    icon: '🔧',
    iconPath: '/icons/specializations/business-development.svg',
    parentIds: ['production_service'],
  },
{
    id: 'quality_engineer',
    name: 'Инженер по качеству',
    icon: '✅',
    iconPath: '/icons/specializations/quality-control.svg',
    parentIds: ['production_service'],
  },
{
    id: 'safety_engineer',
    name: 'Инженер по охране труда и технике безопасности, инженер-эколог',
    icon: '🛡️',
    iconPath: '/icons/specializations/labor-safety.svg',
    parentIds: ['production_service'],
  },
{
    id: 'operation_engineer',
    name: 'Инженер по эксплуатации',
    icon: '⚙️',
    iconPath: '/icons/specializations/helmet.svg',
    parentIds: ['production_service'],
  },
{
    id: 'design_engineer',
    name: 'Инженер-конструктор, инженер-проектировщик',
    icon: '📐',
    iconPath: '/icons/specializations/hands-wrench.svg',
    parentIds: ['production_service'],
  },
{
    id: 'electronic_engineer',
    name: 'Инженер-электроник, инженер-электронщик',
    icon: '🔌',
    iconPath: '/icons/specializations/electric-power-2.svg',
    parentIds: ['production_service'],
  },
{
    id: 'electrical_engineer',
    name: 'Инженер-энергетик, инженер-электрик',
    icon: '⚡',
    iconPath: '/icons/specializations/hand-holding-lightning.svg',
    parentIds: ['production_service'],
  },
{
    id: 'quality_controller',
    name: 'Контролёр ОТК',
    icon: '🔍',
    iconPath: '/icons/specializations/equalizer.svg',
    parentIds: ['production_service'],
  },
{
    id: 'equipment_repair_master',
    name: 'Мастер по ремонту оборудования, техники',
    icon: '🔧',
    iconPath: '/icons/specializations/repair.svg',
    parentIds: ['production_service'],
  },
{
    id: 'metrologist',
    name: 'Метролог',
    icon: '📏',
    iconPath: '/icons/specializations/measure.svg',
    parentIds: ['production_service'],
  },
{
    id: 'production_mechanic',
    name: 'Механик',
    icon: '🔧',
    iconPath: '/icons/specializations/mechanic.svg',
    parentIds: ['production_service', 'working_personnel'],
  },
{
    id: 'production_line_operator',
    name: 'Оператор производственной линии',
    icon: '🏭',
    iconPath: '/icons/specializations/conveyor-belt.svg',
    parentIds: ['production_service', 'working_personnel'],
  },
{
    id: 'cnc_operator',
    name: 'Оператор станков с ЧПУ',
    icon: '🖥️',
    iconPath: '/icons/specializations/3d-printing.svg',
    parentIds: ['production_service', 'working_personnel'],
  },
{
    id: 'production_welder',
    name: 'Сварщик',
    icon: '🔥',
    iconPath: '/icons/specializations/welder.svg',
    parentIds: ['production_service', 'working_personnel'],
  },
{
    id: 'service_engineer',
    name: 'Сервисный инженер, инженер-механик',
    icon: '🔧',
    iconPath: '/icons/specializations/technical-service.svg',
    parentIds: ['production_service', 'working_personnel', 'agriculture'],
  },
{
    id: 'production_locksmith',
    name: 'Слесарь, сантехник',
    icon: '🔧',
    iconPath: '/icons/specializations/faucet.svg',
    parentIds: ['production_service', 'working_personnel'],
  },
{
    id: 'turner_milling_machine_operator',
    name: 'Токарь, фрезеровщик, шлифовщик',
    icon: '⚙️',
    iconPath: '/icons/specializations/laser.svg',
    parentIds: ['production_service', 'working_personnel'],
  },
{
    id: 'seamstress',
    name: 'Швея, портной, закройщик',
    icon: '🧵',
    iconPath: '/icons/specializations/sewing-machine.svg',
    parentIds: ['production_service'],
  },
{
    id: 'production_electrician',
    name: 'Электромонтажник',
    icon: '⚡',
    iconPath: '/icons/specializations/panel.svg',
    parentIds: ['production_service', 'working_personnel'],
  },
{
    id: 'loader',
    name: 'Грузчик',
    icon: '📦',
    iconPath: '/icons/specializations/delivery-man.svg',
    parentIds: ['working_personnel', 'transport_logistics'],
  },
{
    id: 'storekeeper',
    name: 'Кладовщик',
    icon: '📦',
    iconPath: '/icons/specializations/cart.svg',
    parentIds: ['working_personnel', 'transport_logistics'],
  },
{
    id: 'worker_painter',
    name: 'Маляр, штукатур',
    icon: '🎨',
    iconPath: '/icons/specializations/painter.svg',
    parentIds: ['working_personnel'],
  },
{
    id: 'assembler',
    name: 'Монтажник',
    icon: '🔧',
    iconPath: '/icons/specializations/toolbox.svg',
    parentIds: ['working_personnel'],
  },
{
    id: 'general_worker',
    name: 'Разнорабочий',
    icon: '👷',
    iconPath: '/icons/specializations/multitasking.svg',
    parentIds: ['working_personnel'],
  },
{
    id: 'packer',
    name: 'Упаковщик, комплектовщик',
    icon: '📦',
    iconPath: '/icons/specializations/package.svg',
    parentIds: ['working_personnel', 'transport_logistics'],
  },
{
    id: 'store_administrator',
    name: 'Администратор магазина, администратор торгового зала',
    icon: '🏪',
    iconPath: '/icons/specializations/manager-2.svg',
    parentIds: ['retail'],
  },
{
    id: 'store_director',
    name: 'Директор магазина, директор сети магазинов',
    icon: '👔',
    iconPath: '/icons/specializations/boss.svg',
    parentIds: ['retail'],
  },
{
    id: 'merchandiser',
    name: 'Мерчандайзер',
    icon: '📊',
    iconPath: '/icons/specializations/inventory.svg',
    parentIds: ['retail'],
  },
{
    id: 'supervisor',
    name: 'Супервайзер',
    icon: '👁️',
    iconPath: '/icons/specializations/woman-leader.svg',
    parentIds: ['retail'],
  },
{
    id: 'merchandising_specialist',
    name: 'Товаровед',
    icon: '📋',
    iconPath: '/icons/specializations/box.svg',
    parentIds: ['retail'],
  },
{
    id: 'agronomist',
    name: 'Агроном',
    icon: '🌱',
    iconPath: '/icons/specializations/growing-plant.svg',
    parentIds: ['agriculture'],
  },
{
    id: 'zootechnician',
    name: 'Зоотехник',
    icon: '🐄',
    iconPath: '/icons/specializations/species.svg',
    parentIds: ['agriculture'],
  },
{
    id: 'cosmetologist',
    name: 'Косметолог',
    icon: '💆',
    iconPath: '/icons/specializations/cleansing.svg',
    parentIds: ['sports_fitness_beauty'],
  },
{
    id: 'massage_therapist',
    name: 'Массажист',
    icon: '💆',
    iconPath: '/icons/specializations/massage.svg',
    parentIds: ['sports_fitness_beauty'],
  },
{
    id: 'nail_technician',
    name: 'Мастер ногтевого сервиса',
    icon: '💅',
    iconPath: '/icons/specializations/nail-polish.svg',
    parentIds: ['sports_fitness_beauty'],
  },
{
    id: 'hairdresser',
    name: 'Парикмахер',
    icon: '💇',
    iconPath: '/icons/specializations/hair-styling.svg',
    parentIds: ['sports_fitness_beauty'],
  },
{
    id: 'fitness_trainer',
    name: 'Фитнес-тренер, инструктор тренажерного зала',
    icon: '🏋️',
    iconPath: '/icons/specializations/muscle.svg',
    parentIds: ['sports_fitness_beauty'],
  },
{
    id: 'strategy_consultant',
    name: 'Менеджер/консультант по стратегии',
    icon: '💼',
    iconPath: '/icons/specializations/strategy.svg',
    parentIds: ['strategy_investment_consulting'],
  },
{
    id: 'financial_analyst',
    name: 'Финансовый аналитик, инвестиционный аналитик',
    icon: '💹',
    iconPath: '/icons/specializations/analytics-2.svg',
    parentIds: ['strategy_investment_consulting', 'finance_accounting'],
  },
{
    id: 'underwriter',
    name: 'Андеррайтер',
    icon: '📝',
    iconPath: '/icons/specializations/project-management.svg',
    parentIds: ['insurance'],
  },
{
    id: 'appraiser',
    name: 'Оценщик',
    icon: '📊',
    iconPath: '/icons/specializations/search.svg',
    parentIds: ['insurance'],
  },
{
    id: 'flight_attendant',
    name: 'Бортпроводник',
    icon: '✈️',
    iconPath: '/icons/specializations/stewardess.svg',
    parentIds: ['transport_logistics'],
  },
{
    id: 'dispatcher',
    name: 'Диспетчер',
    icon: '📞',
    iconPath: '/icons/specializations/operator.svg',
    parentIds: ['transport_logistics'],
  },
{
    id: 'logistics_manager',
    name: 'Менеджер по логистике, менеджер по ВЭД',
    icon: '📋',
    iconPath: '/icons/specializations/container.svg',
    parentIds: ['transport_logistics'],
  },
{
    id: 'warehouse_manager',
    name: 'Начальник склада',
    icon: '🏢',
    iconPath: '/icons/specializations/warehouse.svg',
    parentIds: ['transport_logistics'],
  },
{
    id: 'tourism_manager',
    name: 'Менеджер по туризму',
    icon: '🗺️',
    iconPath: '/icons/specializations/tour-guide.svg',
    parentIds: ['tourism_hotels_restaurants'],
  },
{
    id: 'restaurant_manager',
    name: 'Менеджер ресторана',
    icon: '🍽️',
    iconPath: '/icons/specializations/referee.svg',
    parentIds: ['tourism_hotels_restaurants'],
  },
{
    id: 'chef',
    name: 'Повар, пекарь, кондитер',
    icon: '👨‍🍳',
    iconPath: '/icons/specializations/chef.svg',
    parentIds: ['tourism_hotels_restaurants'],
  },
{
    id: 'hostess',
    name: 'Хостес',
    icon: '💁',
    iconPath: '/icons/specializations/woman.svg',
    parentIds: ['tourism_hotels_restaurants'],
  },
{
    id: 'compensation_manager',
    name: 'Менеджер по компенсациям и льготам',
    icon: '💰',
    iconPath: '/icons/specializations/cashback.svg',
    parentIds: ['hr_training'],
  },
{
    id: 'hr_manager',
    name: 'Менеджер по персоналу',
    icon: '👥',
    iconPath: '/icons/specializations/leadership.svg',
    parentIds: ['hr_training'],
  },
{
    id: 'hr_specialist',
    name: 'Специалист по кадрам',
    icon: '📋',
    iconPath: '/icons/specializations/hr-2.svg',
    parentIds: ['hr_training'],
  },
{
    id: 'recruiter',
    name: 'Специалист по подбору персонала',
    icon: '🔍',
    iconPath: '/icons/specializations/choose.svg',
    parentIds: ['hr_training'],
  },
{
    id: 'auditor',
    name: 'Аудитор',
    icon: '🔍',
    iconPath: '/icons/specializations/audit-document.svg',
    parentIds: ['finance_accounting'],
  },
{
    id: 'accountant',
    name: 'Бухгалтер',
    icon: '💼',
    iconPath: '/icons/specializations/tax.svg',
    parentIds: ['finance_accounting'],
  },
{
    id: 'treasurer',
    name: 'Казначей',
    icon: '💰',
    iconPath: '/icons/specializations/money-bag.svg',
    parentIds: ['finance_accounting'],
  },
{
    id: 'compliance_manager',
    name: 'Комплаенс-менеджер',
    icon: '📋',
    iconPath: '/icons/specializations/planning.svg',
    parentIds: ['finance_accounting', 'legal'],
  },
{
    id: 'debt_collector',
    name: 'Специалист по взысканию задолженности',
    icon: '💸',
    iconPath: '/icons/specializations/bond.svg',
    parentIds: ['finance_accounting'],
  },
{
    id: 'financial_controller',
    name: 'Финансовый контролер',
    icon: '📊',
    iconPath: '/icons/specializations/money.svg',
    parentIds: ['finance_accounting'],
  },
{
    id: 'financial_manager',
    name: 'Финансовый менеджер',
    icon: '💼',
    iconPath: '/icons/specializations/financing-2.svg',
    parentIds: ['finance_accounting'],
  },
{
    id: 'economist',
    name: 'Экономист',
    icon: '📈',
    iconPath: '/icons/specializations/growth.svg',
    parentIds: ['finance_accounting'],
  },
{
    id: 'legal_counsel',
    name: 'Юрисконсульт',
    icon: '⚖️',
    iconPath: '/icons/specializations/lawyer.svg',
    parentIds: ['legal'],
  },
{
    id: 'lawyer',
    name: 'Юрист',
    icon: '⚖️',
    iconPath: '/icons/specializations/lawyer-day.svg',
    parentIds: ['legal'],
  },
{
    id: 'other_category',
    name: 'Другое',
    icon: '📋',
    iconPath: '/icons/specializations/more.svg',
    parentIds: ['other'],
  }
];

// Получить специализацию по ID
export const getSpecializationById = (id: string): SpecializationOption | undefined => {
  // Проверяем сначала в родительских категориях
  const parentSpec = PARENT_CATEGORIES.find(spec => spec.id === id);
  if (parentSpec) return parentSpec;
  
  // Затем в обычных специализациях
  return SPECIALIZATIONS.find(spec => spec.id === id);
};

// Получить подкатегории по родительскому ID
export const getSubcategoriesByParentId = (parentId: string): SpecializationOption[] => {
  return SPECIALIZATIONS.filter(spec => spec.parentIds?.includes(parentId));
};

// Получить категории верхнего уровня (родительские + без родителя)
export const getTopLevelCategories = (): SpecializationOption[] => {
  const topLevelSpecs = SPECIALIZATIONS.filter(spec => !spec.parentIds || spec.parentIds.length === 0);
  // Сначала показываем топ-уровневые специализации, затем родительские категории
  return [...topLevelSpecs, ...PARENT_CATEGORIES];
};

// Получить имя специализации по ID (без перевода - для обратной совместимости)
export const getSpecializationName = (id: string): string => {
  const spec = getSpecializationById(id);
  return spec ? spec.name : id;
};

// Получить иконку специализации по ID
export const getSpecializationIcon = (id: string): string => {
  const spec = getSpecializationById(id);
  return spec ? spec.icon : '🔨';
};

